In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,ReLU,Dropout

In [2]:
data=pd.read_csv('D:\Sandesh\Data Science\Deep Learning\Admission_Predict_Ver1.1.csv')
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [3]:
data.shape

(500, 9)

In [4]:
data.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         500 non-null    int64
 1   GRE Score          500 non-null    int64
 2   TOEFL Score        500 non-null    int64
 3   University Rating  500 non-null    int64
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [6]:
data.duplicated().sum()

0

In [7]:
del data ['Serial No.']

In [8]:
X=data.drop(columns=['Chance of Admit '])
y=data['Chance of Admit ']
X

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)

In [10]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
X_train=minmax.fit_transform(X_train)
X_test=minmax.transform(X_test)

In [11]:
# create a neural network 
model=Sequential()
model.add(Dense(units=10,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=10,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=1,activation='linear'))

In [12]:
model.compile(loss='mean_squared_error',optimizer='adam')

In [13]:
history=model.fit(X_train,y_train,validation_split=0.20,epochs=100)

Epoch 1/100
10/10 [==============================] - 1s 19ms/step - loss: 0.5110 - val_loss: 0.2887
Epoch 2/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4418 - val_loss: 0.1753
Epoch 3/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2884 - val_loss: 0.1116
Epoch 4/100
10/10 [==============================] - 0s 3ms/step - loss: 0.2951 - val_loss: 0.0789
Epoch 5/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2543 - val_loss: 0.0682
Epoch 6/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2230 - val_loss: 0.0684
Epoch 7/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2086 - val_loss: 0.0730
Epoch 8/100
10/10 [==============================] - 0s 3ms/step - loss: 0.1797 - val_loss: 0.0726
Epoch 9/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1988 - val_loss: 0.0651
Epoch 10/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1380 - val_loss: 0.0607
Epoch 11/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1433 - val_loss: 0.0593
Epoch 12/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1354 - val_loss: 0.0563
Epoch 13/100
10/10 [==============================] - 0s 3ms/step - loss: 0.1307 - val_loss: 0.0553
Epoch 14/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1321 - val_loss: 0.0540
Epoch 15/100
10/10 [==============================] - 0s 3ms/step - loss: 0.1081 - val_loss: 0.0533
Epoch 16/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0949 - val_loss: 0.0534
Epoch 17/100
10/10 [==============================] - 0s 4ms/step - loss: 0.1076 - val_loss: 0.0547
Epoch 18/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0877 - val_loss: 0.0515
Epoch 19/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0753 - val_loss: 0.0462
Epoch 20/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0774 - val_loss: 0.0408
Epoch 21/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0763 - val_loss: 0.0366
Epoch 22/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0706 - val_loss: 0.0366
Epoch 23/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0797 - val_loss: 0.0301
Epoch 24/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0622 - val_loss: 0.0276
Epoch 25/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0668 - val_loss: 0.0265
Epoch 26/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0615 - val_loss: 0.0285
Epoch 27/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0551 - val_loss: 0.0287
Epoch 28/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0556 - val_loss: 0.0277
Epoch 29/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0579 - val_loss: 0.0243
Epoch 30/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0502 - val_loss: 0.0215
Epoch 31/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0535 - val_loss: 0.0215
Epoch 32/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0471 - val_loss: 0.0224
Epoch 33/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0511 - val_loss: 0.0215
Epoch 34/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0500 - val_loss: 0.0213
Epoch 35/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0452 - val_loss: 0.0229
Epoch 36/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0474 - val_loss: 0.0221
Epoch 37/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0474 - val_loss: 0.0225
Epoch 38/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0450 - val_loss: 0.0228
Epoch 39/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0462 - val_loss: 0.0231
Epoch 40/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0445 - val_loss: 0.0231
Epoch 41/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0431 - val_loss: 0.0223
Epoch 42/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0394 - val_loss: 0.0206
Epoch 43/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0446 - val_loss: 0.0169
Epoch 44/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0397 - val_loss: 0.0163
Epoch 45/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0379 - val_loss: 0.0178
Epoch 46/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0396 - val_loss: 0.0187
Epoch 47/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0440 - val_loss: 0.0204
Epoch 48/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0399 - val_loss: 0.0204
Epoch 49/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0373 - val_loss: 0.0216
Epoch 50/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0393 - val_loss: 0.0192
Epoch 51/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0391 - val_loss: 0.0189
Epoch 52/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0379 - val_loss: 0.0173
Epoch 53/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0375 - val_loss: 0.0159
Epoch 54/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0354 - val_loss: 0.0159
Epoch 55/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0331 - val_loss: 0.0166
Epoch 56/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0337 - val_loss: 0.0172
Epoch 57/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0352 - val_loss: 0.0168
Epoch 58/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0395 - val_loss: 0.0170
Epoch 59/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0351 - val_loss: 0.0157
Epoch 60/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0320 - val_loss: 0.0146
Epoch 61/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0389 - val_loss: 0.0149
Epoch 62/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0342 - val_loss: 0.0156
Epoch 63/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0322 - val_loss: 0.0157
Epoch 64/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0377 - val_loss: 0.0161
Epoch 65/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0372 - val_loss: 0.0149
Epoch 66/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0328 - val_loss: 0.0137
Epoch 67/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0341 - val_loss: 0.0133
Epoch 68/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0350 - val_loss: 0.0136
Epoch 69/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0292 - val_loss: 0.0133
Epoch 70/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0308 - val_loss: 0.0131
Epoch 71/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0343 - val_loss: 0.0146
Epoch 72/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0282 - val_loss: 0.0151
Epoch 73/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0317 - val_loss: 0.0161
Epoch 74/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0270 - val_loss: 0.0161
Epoch 75/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0285 - val_loss: 0.0154
Epoch 76/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0335 - val_loss: 0.0141
Epoch 77/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0247 - val_loss: 0.0134
Epoch 78/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0263 - val_loss: 0.0132
Epoch 79/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0256 - val_loss: 0.0139
Epoch 80/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0249 - val_loss: 0.0141
Epoch 81/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0253 - val_loss: 0.0136
Epoch 82/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0268 - val_loss: 0.0128
Epoch 83/100

10/10 [==============================] - 0s 4ms/step - loss: 0.0276 - val_loss: 0.0124
Epoch 84/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0285 - val_loss: 0.0117
Epoch 85/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0259 - val_loss: 0.0120
Epoch 86/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0261 - val_loss: 0.0123
Epoch 87/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0291 - val_loss: 0.0122
Epoch 88/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0261 - val_loss: 0.0121
Epoch 89/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0288 - val_loss: 0.0115
Epoch 90/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0237 - val_loss: 0.0107
Epoch 91/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0272 - val_loss: 0.0109
Epoch 92/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0218 - val_loss: 0.0112
Epoch 93/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0261 - val_loss: 0.0123
Epoch 94/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0220 - val_loss: 0.0130
Epoch 95/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0249 - val_loss: 0.0125
Epoch 96/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0275 - val_loss: 0.0114
Epoch 97/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0224 - val_loss: 0.0110
Epoch 98/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0244 - val_loss: 0.0113
Epoch 99/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0209 - val_loss: 0.0123
Epoch 100/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0219 - val_loss: 0.0132

In [14]:
from sklearn.metrics import mean_squared_error,r2_score
y_predict=model.predict(X_test)
print(r2_score(y_test,y_predict))

0.264583366534751

### THE END